packages:
  - packages/*
  - packages/core/base/*
  - apps/*
catalog:
  bumpp: ^10.2.0
  eslint-plugin-prettier: ^5.2.3
  eslint-plugin-vitest: ^0.5.4
  eslint-plugin-vue: ^10.0.0
  eslint: ^9.22.0
  lefthook: ^1.12.2
  lint-staged: ^15.4.3
  prettier-plugin-tailwindcss: ^0.6.11
  prettier: ^3.5.3
  vitepress: ^1.6.3
  vue-router: ^4.5.0
  vue: ^3.5.13
