packages:
  - packages/*
  - packages/core/base/*
  - apps/*

catalog:
  '@eslint/js': ^9.30.1
  '@types/eslint': ^9.6.1
  '@typescript-eslint/eslint-plugin': ^8.35.1
  '@typescript-eslint/parser': ^8.35.1
  bumpp: ^10.2.0
  eslint-config-turbo: ^2.5.4
  eslint-plugin-command: ^3.3.1
  eslint-plugin-eslint-comments: ^3.2.0
  eslint-plugin-import-x: ^4.16.1
  eslint-plugin-jsdoc: ^51.4.0
  eslint-plugin-jsonc: ^2.20.1
  eslint-plugin-n: ^17.20.0
  eslint-plugin-no-only-tests: ^3.3.0
  eslint-plugin-perfectionist: ^4.15.0
  eslint-plugin-prettier: ^5.5.1
  eslint-plugin-regexp: ^2.9.0
  eslint-plugin-unicorn: ^59.0.1
  eslint-plugin-unused-imports: ^4.1.4
  eslint-plugin-vitest: ^0.5.4
  eslint-plugin-vue: ^10.2.0
  eslint: ^9.30.1
  globals: ^16.3.0
  jsonc-eslint-parser: ^2.4.0
  lefthook: ^1.12.2
  lint-staged: ^15.4.3
  prettier-plugin-tailwindcss: ^0.6.14
  prettier: ^3.6.2
  unbuild: ^3.5.0
  vitepress: ^1.6.3
  vue-eslint-parser: ^10.2.0
  vue-router: ^4.5.0
  vue: ^3.5.17

onlyBuiltDependencies:
  - esbuild
  - lefthook
  - unrs-resolver
